name: EnderDragonFridays
main: com.SkyIsland.EnderDragonFridays.EnderDragonFridaysPlugin
version: 0.1
softdepend: [LWCPlugin] 
permissions:
    enderdragonfridays.*:
        children:
            enderdragonfridays.startdragonfight: true
            enderdragonfridays.killdragon: true
            enderdragonfridays.killalldragons: true
            enderdragonfridays.windragonwars: true
            enderdragonfridays.setcontribution: true
        default: op
    enderdragonfridays.startdragonfight:
        default: op
    enderdragonfridays.killdragon:
        default: op
    enderdragonfridays.killalldragons:
        default: op
    enderdragonfridays.windragonwars:
        default: op
    enderdragonfridays.setcontribution:
        default: op
commands:
    killalldragons:
        description: Kills all ender dragons in the world
        usage: /killalldragons
        permission: enderdragonfridays.killalldragons
    enderdragonfridays:
        permission: enderdragonfridays.*
        usage: /edf [create, reload, start]
        description: Executes a command for ender dragon fridays plugin
        aliases: edf
    setcontribution:
        permission: enderdragonfridays.setcontribution
        usage: /setcontribution contribution
