name: EnderDragonFridays
main: com.SkyIsland.EnderDragonFridays.EnderDragonFridaysPlugin
version: 0.1
softdepend: [LWCPlugin] 
commands:
    makestuff:
        description: who knows!
        usage: /makestuff
        permission: bukkit.command.ban.player
    killdragon:
        description: kills a dragon!
        usage: /killdragon
        permission: bukkit.command.ban.player
    killalldragons:
        description: Kills all ender dragons in the world
        usage: /killalldragons
        permission: bukkit.command.ban.player
    enderdragonfridays:
        permission: bukkit.command.ban.player
        usage: /edf [reload]
        description: Executes a command for ender dragon fridays plugin
        aliases: edf
    windragonwars:
        permission: bukkit.command.ban.player
        usage: /windragonwars